/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taboadaannunziatameetingatleticaleggera;

import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JButton;

/**
 *
 * @author taboada.taddeo
 */
public class FrameMeeting extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameMeeting.class.getName());
    private String scelta;
    private Meeting m;

    /**
     * Creates new form FrameMeeting
     */
    public FrameMeeting(Meeting m) {
        initComponents();
        caricaImmagini();
        this.m = m;
    }
    
    public void apriFrameCompetizione() {
        FrameCompetizione fC = new FrameCompetizione(this, m, scelta);
        this.setVisible(false);
        fC.setLocationRelativeTo(null);
        fC.setVisible(true);
    }
    
     private void caricaImmagini() {
        // Immagine 100 Metri
        ImageIcon icon100M = new ImageIcon("img/100metri.png");
        Image img100M = icon100M.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        lblImmagineCM.setIcon(new ImageIcon(img100M));
        lblImmagineCM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Immagine Corsa a Ostacoli
        ImageIcon iconCO = new ImageIcon("img/corsaostacoli.png");
        Image imgCO = iconCO.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        lblImmagineCO.setIcon(new ImageIcon(imgCO));
        lblImmagineCO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Immagine Lancio Giavellotto
        ImageIcon iconLG = new ImageIcon("img/giavellotto.png");
        Image imgLG = iconLG.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        lblImmagineLG.setIcon(new ImageIcon(imgLG));
        lblImmagineLG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // Immagine Lancio Martello
        ImageIcon iconLM = new ImageIcon("img/martello.png");
        Image imgLM = iconLM.getImage().getScaledInstance(400, 400, Image.SCALE_SMOOTH);
        lblImmagineLM.setIcon(new ImageIcon(imgLM));
        lblImmagineLM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }

    public JButton getBtnRisultati() {
        return btnRisultati;
    }

    public void setM(Meeting m) {
        this.m = m;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        btnRisultati = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCentoMetri = new javax.swing.JLabel();
        lblCorsaOstacoli = new javax.swing.JLabel();
        lblLancioGiavellotto = new javax.swing.JLabel();
        lblLancioMartello = new javax.swing.JLabel();
        lblImmagineCM = new javax.swing.JLabel();
        lblImmagineCO = new javax.swing.JLabel();
        lblImmagineLG = new javax.swing.JLabel();
        lblImmagineLM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCentoMetri = new javax.swing.JButton();
        btnCorsaOstacoli = new javax.swing.JButton();
        btnLancioGiavellotto = new javax.swing.JButton();
        btnLancioMartello = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meeting Atletica Leggera");
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Meeting Atletica Leggera");
        lblTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnRisultati.setText("Risultati");
        btnRisultati.setEnabled(false);
        btnRisultati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRisultatiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(lblTitolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(btnRisultati, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitolo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRisultati, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblCentoMetri.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCentoMetri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCentoMetri.setText("100 Metri");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblCentoMetri, gridBagConstraints);

        lblCorsaOstacoli.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCorsaOstacoli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorsaOstacoli.setText("Corsa a Ostacoli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblCorsaOstacoli, gridBagConstraints);

        lblLancioGiavellotto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLancioGiavellotto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLancioGiavellotto.setText("Lancio del Giavellotto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblLancioGiavellotto, gridBagConstraints);

        lblLancioMartello.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLancioMartello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLancioMartello.setText("Lancio del Martello");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblLancioMartello, gridBagConstraints);

        lblImmagineCM.setAutoscrolls(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblImmagineCM, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblImmagineCO, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblImmagineLG, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 6);
        jPanel1.add(lblImmagineLM, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 10));

        btnCentoMetri.setText("Gioca 100 Metri");
        btnCentoMetri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentoMetriActionPerformed(evt);
            }
        });
        jPanel2.add(btnCentoMetri);

        btnCorsaOstacoli.setText("Gioca Corsa a Ostacoli");
        btnCorsaOstacoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorsaOstacoliActionPerformed(evt);
            }
        });
        jPanel2.add(btnCorsaOstacoli);

        btnLancioGiavellotto.setText("Gioca al lancio del giavellotto");
        btnLancioGiavellotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancioGiavellottoActionPerformed(evt);
            }
        });
        jPanel2.add(btnLancioGiavellotto);

        btnLancioMartello.setText("Gioca al lancio del martello");
        btnLancioMartello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancioMartelloActionPerformed(evt);
            }
        });
        jPanel2.add(btnLancioMartello);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCentoMetriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentoMetriActionPerformed
        scelta = "CentoMetri";
        apriFrameCompetizione();
    }//GEN-LAST:event_btnCentoMetriActionPerformed

    private void btnCorsaOstacoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorsaOstacoliActionPerformed
        scelta = "CorsaOstacoli";
        apriFrameCompetizione();
    }//GEN-LAST:event_btnCorsaOstacoliActionPerformed

    private void btnLancioGiavellottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancioGiavellottoActionPerformed
        scelta = "LancioGiavellotto";
        apriFrameCompetizione();
    }//GEN-LAST:event_btnLancioGiavellottoActionPerformed

    private void btnLancioMartelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancioMartelloActionPerformed
        scelta = "LancioMartello";
        apriFrameCompetizione();
    }//GEN-LAST:event_btnLancioMartelloActionPerformed

    private void btnRisultatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRisultatiActionPerformed
        Risultati r = new Risultati(this, true);
        r.setBounds(0, 0, this.getWidth() / 2, this.getHeight() / 2);
        r.setLocationRelativeTo(null);
        r.stampaRisultati(m);
        r.setVisible(true);
    }//GEN-LAST:event_btnRisultatiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentoMetri;
    private javax.swing.JButton btnCorsaOstacoli;
    private javax.swing.JButton btnLancioGiavellotto;
    private javax.swing.JButton btnLancioMartello;
    private javax.swing.JButton btnRisultati;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCentoMetri;
    private javax.swing.JLabel lblCorsaOstacoli;
    private javax.swing.JLabel lblImmagineCM;
    private javax.swing.JLabel lblImmagineCO;
    private javax.swing.JLabel lblImmagineLG;
    private javax.swing.JLabel lblImmagineLM;
    private javax.swing.JLabel lblLancioGiavellotto;
    private javax.swing.JLabel lblLancioMartello;
    private javax.swing.JLabel lblTitolo;
    // End of variables declaration//GEN-END:variables
}
