/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taboadaannunziatameetingatleticaleggera;

import javax.swing.JFrame;

/**
 *
 * @author utente
 */
public class FrameCompetizione extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameCompetizione.class.getName());
    private Gara g;
    private FrameMeeting frameMeeting;
    private Meeting m;
    private String scelta = "";
    
    /**
     * Creates new form FrameCompetizione
     * @param scelta
     */
    public FrameCompetizione(FrameMeeting frameMeeting, Meeting m, String scelta) {
        initComponents();
        this.frameMeeting = frameMeeting;
        this.m = m;
        this.scelta = scelta;
        trovaScelta();
    }

    public void apriFrameMeeting() {
        this.setVisible(false);
        frameMeeting.setVisible(true);
        frameMeeting.getBtnRisultati().setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNazionalita = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblNazionalita = new javax.swing.JLabel();
        btnConferma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxGara = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        atxAtleti = new javax.swing.JTextArea();
        btnGioca = new javax.swing.JButton();
        btnRimuovi = new javax.swing.JButton();
        cmbAtleti = new javax.swing.JComboBox<>();
        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Competizione Atletica Leggera");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Numero");

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome");
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblNazionalita.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNazionalita.setText("Nazionalità");

        btnConferma.setText("Conferma");
        btnConferma.addActionListener(this::btnConfermaActionPerformed);

        atxGara.setColumns(20);
        atxGara.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atxGara.setRows(5);
        atxGara.setEnabled(false);
        jScrollPane1.setViewportView(atxGara);

        atxAtleti.setColumns(20);
        atxAtleti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atxAtleti.setRows(5);
        atxAtleti.setEnabled(false);
        jScrollPane2.setViewportView(atxAtleti);

        btnGioca.setText("Gioca");
        btnGioca.setEnabled(false);
        btnGioca.addActionListener(this::btnGiocaActionPerformed);

        btnRimuovi.setText("Rimuovi Atleta");
        btnRimuovi.addActionListener(this::btnRimuoviActionPerformed);

        cmbAtleti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNazionalita, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(lblNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNazionalita, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRimuovi, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(cmbAtleti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(btnGioca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGioca)
                    .addComponent(btnRimuovi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNazionalita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNazionalita)
                            .addComponent(cmbAtleti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(btnConferma)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlTitolo.setBackground(new java.awt.Color(0, 204, 204));

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Competizione");
        lblTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnMenu.setText("Menu");
        btnMenu.setPreferredSize(new java.awt.Dimension(75, 75));
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        javax.swing.GroupLayout pnlTitoloLayout = new javax.swing.GroupLayout(pnlTitolo);
        pnlTitolo.setLayout(pnlTitoloLayout);
        pnlTitoloLayout.setHorizontalGroup(
            pnlTitoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        pnlTitoloLayout.setVerticalGroup(
            pnlTitoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitoloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitoloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trovaScelta() {
        switch (scelta) {
            case "CentoMetri":
                g = new CentoMetri("100 metri piani");
                break;
            case "CorsaOstacoli":
                g = new CorsaOstacoli("110 metri ad ostacoli");
                break;
            case "LancioGiavellotto":
                g = new LancioGiavellotto("Lancio del Giavellotto");
                break;
            case "LancioMartello":
                g = new LancioMartello("Lancio del Martello");
                break;
            default:
                break;
        }
        m.aggiungiGara(g);
        lblTitolo.setText(g.getNome());
    }

    public Meeting getM() {
        return m;
    }
    
    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        String nome = txtNome.getText();
        String nazionalita = txtNazionalita.getText();
        String numero = txtNumero.getText();
        
        if (scelta.equals("CentoMetri") || scelta.equals("CorsaOstacoli")) {
            Velocista v = new Velocista(nome, nazionalita, numero);
            g.getAtleti().add(v);
            atxAtleti.append(v.atletaToString() + "\n");
        } else if (scelta.equals("LancioGiavellotto") || scelta.equals("LancioMartello")) {
            Lanciatore l = new Lanciatore(nome, nazionalita, numero);
            g.getAtleti().add(l);
            atxAtleti.append(l.atletaToString() + "\n");
        }
        
        cmbAtleti.addItem(nome);
        
        btnGioca.setEnabled(true);
    }//GEN-LAST:event_btnConfermaActionPerformed

    private void btnGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiocaActionPerformed
        btnGioca.setEnabled(false);
        g.gioca();
        atxGara.setText(g.stampaRisultato());
    }//GEN-LAST:event_btnGiocaActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        apriFrameMeeting();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviActionPerformed
        for (Atleta a: g.getAtleti()) {
            if (cmbAtleti.getSelectedItem().equals(a.getNome())) {
                cmbAtleti.removeItem(cmbAtleti.getSelectedItem());
                g.rimuoviAtleta(a);
                btnGioca.setEnabled(true);
            }
            break;
        }
    }//GEN-LAST:event_btnRimuoviActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxAtleti;
    private javax.swing.JTextArea atxGara;
    private javax.swing.JButton btnConferma;
    private javax.swing.JButton btnGioca;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRimuovi;
    private javax.swing.JComboBox<String> cmbAtleti;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNazionalita;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JTextField txtNazionalita;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
