/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package taboadaannunziatameetingatleticaleggera;

/**
 *
 * @author taboada.taddeo
 */
public class Risultati extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Risultati.class.getName());

    /**
     * Costruttore di FrameCompetizione
     * @param parent frame da cui parte il JDialog, in questo caso FrameMeeting
     * @param modal booleano che se true, richiede una risposta dall'utente prima di interagire con il resto della frame, altrimenti false
     */
    public Risultati(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxRisultati = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Risultati delle Gare");
        setBackground(new java.awt.Color(0, 204, 204));

        btnOk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, java.awt.BorderLayout.PAGE_END);

        atxRisultati.setColumns(20);
        atxRisultati.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atxRisultati.setRows(5);
        atxRisultati.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        atxRisultati.setEnabled(false);
        jScrollPane1.setViewportView(atxRisultati);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo che stampa i risultati delle gare
     * @param m il meeting da cui vengono prese le gare
     */
    public void stampaRisultati(Meeting m) {
        atxRisultati.setText("");
        atxRisultati.append("=== Ecco i risultati delle gare === \n");
        for (Gara g : m.getEventi()) {
            atxRisultati.append("\n" + g.stampaRisultato());
        }
    }
    
    /**
     * Metodo che chiude la JDialog
     * @param evt click del bottone btnOk
     */
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Risultati dialog = new Risultati(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxRisultati;
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
